version: "3.1"

services:
  database:
    image: mysql:5.7
    container_name: raro_tube_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= root
    ports:
      - 3306:3306
    volumes:
      - raro_tube:/var/lib/mysql

  app:
    build: .
    command: npm run dev
    container_name: raro_tube
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
   

volumes:
  raro_tube:
    driver: local
