version: "3.1"

services:
  database:
    image: mysql:5.7
    container_name: raro_tube_db
    restart: always
    environment:
      - MYSQL_DATABASE= ra_drive_monia_lodo
      - MYSQL_HOST=44.199.200.211
      - MYSQL_ROOT_PASSWORD= 2C4F4D51-A37D-4B59-B0E4-EFB945137ED5
    ports:
      - 3307:3307
    volumes:
      - raro_tube:/var/lib/mysql

  app:
    build: .
    command: npm run dev
    container_name: raro_tube
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - NODE_PORT=3000
      - NODE_HOST=localhost
      - MYSQL_HOST=44.199.200.211
      - MYSQL_PORT=3307
      - MYSQL_USER=monia_lodo
      - MYSQL_PASSWORD=2C4F4D51-A37D-4B59-B0E4-EFB945137ED5
      - MYSQL_DATABASE=ra_drive_monia_lodo
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
   

volumes:
  raro_tube:
    driver: local
