version: "3.1"

services:
  database:
    image: postgres 
    container_name: raro_tube_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=raro
      - POSTGRES_PASSWORD=raro
      - POSTGRES_DB=raro_tube

    volumes:
      - raro_tube:/data/postgres

  app:
    build: .
    command: npm run dev
    container_name: raro_tube
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  raro_tube:
    driver: local